apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-storage-claim
  namespace: yessinemimita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
